---
- hosts: all
  user: ec2-user
  become: yes
  tasks:
  # - name: Insert setting the selinux/config
  #   blockinfile:
  #     path: /etc/selinux/config
  #     insertafter: 'EOF'
  #     block: |
  #       SELINUX=permissiv
  - name: Insert setting the ansible/config
    blockinfile:
      path: /etc/ansible/ansible.cfg
      insertafter: 'EOF'
      block: |
        command_warnings=False
  - name:  yum update os rhel
    shell: yum update -y
    warn: false
    #command_warnings=False
  - name: reboot the instance
    shell: sudo init 6